# Generated by Django 3.2.4 on 2021-08-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_feedbackrequest_essay_given_by_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='feedback_Created_Date',
        ),
    ]
